### ISSUE TITLE
部分情形下刷新页面或重新打开网站会导致数据丢失或显示错误

### ISSUE THREAD

**Issue by Zhehan-Z** [yemaster/vstc#2]
## 问题概述
主测试页面上的 unload 和 onBeforeUnmount 触发保存，不能做到安全保存所有的答题进度。

## 影响情况
目前有以下几种情况可以复现：
- 在微信浏览器中任意答题并关闭页面，再次打开时没有答题记录。（iOS 微信 8.0.54，关闭/刷新不能触发保存)
- 在微信浏览器中答题“思想道德与法治”并关闭页面，再次打开时不仅没有答题记录，首页点击推荐的“思想道德与法治”甚至有概率会错误进入校规测试页面。（iOS 微信 8.0.54，关闭/刷新不能触发保存）
- 在 iPhone/iPad Safari 浏览器中，答题提交，在不前往其他页面触发保存机制的情况下直接关闭页面（或者浏览器的后台机制暂停或冻结了页面），再次打开时缺失部分甚至全部答题记录。（iOS 18.1，强制关闭不能触发保存，有时刷新可以触发保存）

## 潜在解决方案
- 判定一题存一题（最安全）
- 每n道题存一次
- 用Watcher观测，动态数据一变化就存

## 临时绕过
- 答题时主动点击页面链接切换到网站其他页面，触发保存。
- 主动下载备份答题进度，丢了就上传回来。

感谢开发者付出。

**Comment by Davidasx** [comment]
@Danielccbb0530

**Comment by Zhehan-Z** [comment]
已提交 PR #3 ，通过判定一道存一道的方式确保数据安全。 @yemaster
